spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhongzunfa/spring-cloud-config.git
          #username:
          #password:
          search-paths: SC-BOOK-CONFIG
  application:
    name: sc-config-git
server:
    port: 9090