server:
  port: 8010
spring:
  application:
    name: crm-sales-consumer

eureka:
  client:
    service-url:
           defaultZone: http://eureka.springcloud.cn/eureka/
    instance:
        prefer-ip-address: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000